"""add missing tables for fresh install

Revision ID: dd2e2d166c43
Revises: 11456e96ecba
Create Date: 2026-05-20 16:51:11.010565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd2e2d166c43'
down_revision: Union[str, Sequence[str], None] = '11456e96ecba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('target_role', sa.String(length=30), nullable=False),
    sa.Column('target_course_id', sa.String(length=100), nullable=True),
    sa.Column('submit_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_surveys_id'), 'onboarding_surveys', ['id'], unique=False)
    op.create_index(op.f('ix_onboarding_surveys_status'), 'onboarding_surveys', ['status'], unique=False)
    op.create_index(op.f('ix_onboarding_surveys_survey_id'), 'onboarding_surveys', ['survey_id'], unique=True)
    op.create_index(op.f('ix_onboarding_surveys_target_role'), 'onboarding_surveys', ['target_role'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_table('onboarding_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(length=50), nullable=False),
    sa.Column('survey_id', sa.String(length=50), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('subtitle', sa.String(length=500), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('matrix_items', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['onboarding_surveys.survey_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_questions_id'), 'onboarding_questions', ['id'], unique=False)
    op.create_index(op.f('ix_onboarding_questions_question_id'), 'onboarding_questions', ['question_id'], unique=True)
    op.create_index(op.f('ix_onboarding_questions_survey_id'), 'onboarding_questions', ['survey_id'], unique=False)
    op.create_table('course_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_files_id'), 'course_files', ['id'], unique=False)
    op.create_table('onboarding_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.String(length=50), nullable=False),
    sa.Column('question_id', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('profile_mapping', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['onboarding_questions.question_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_options_id'), 'onboarding_options', ['id'], unique=False)
    op.create_index(op.f('ix_onboarding_options_option_id'), 'onboarding_options', ['option_id'], unique=True)
    op.create_index(op.f('ix_onboarding_options_question_id'), 'onboarding_options', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarding_options_question_id'), table_name='onboarding_options')
    op.drop_index(op.f('ix_onboarding_options_option_id'), table_name='onboarding_options')
    op.drop_index(op.f('ix_onboarding_options_id'), table_name='onboarding_options')
    op.drop_table('onboarding_options')
    op.drop_index(op.f('ix_course_files_id'), table_name='course_files')
    op.drop_table('course_files')
    op.drop_index(op.f('ix_onboarding_questions_survey_id'), table_name='onboarding_questions')
    op.drop_index(op.f('ix_onboarding_questions_question_id'), table_name='onboarding_questions')
    op.drop_index(op.f('ix_onboarding_questions_id'), table_name='onboarding_questions')
    op.drop_table('onboarding_questions')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_onboarding_surveys_target_role'), table_name='onboarding_surveys')
    op.drop_index(op.f('ix_onboarding_surveys_survey_id'), table_name='onboarding_surveys')
    op.drop_index(op.f('ix_onboarding_surveys_status'), table_name='onboarding_surveys')
    op.drop_index(op.f('ix_onboarding_surveys_id'), table_name='onboarding_surveys')
    op.drop_table('onboarding_surveys')
    # ### end Alembic commands ###
