"""add_profile_dialogue_tables

Revision ID: e640fcc4f3ae
Revises: 819a6fd56de9
Create Date: 2026-05-27 22:04:57.999725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e640fcc4f3ae'
down_revision: Union[str, Sequence[str], None] = '819a6fd56de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_dialogue_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('scene', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_slot', sa.String(length=50), nullable=False),
    sa.Column('collected_slots_json', sa.JSON(), nullable=False),
    sa.Column('missing_slots_json', sa.JSON(), nullable=False),
    sa.Column('extracted_fields_json', sa.JSON(), nullable=False),
    sa.Column('profile_preview_json', sa.JSON(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_dialogue_sessions_id'), 'profile_dialogue_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_profile_dialogue_sessions_status'), 'profile_dialogue_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_profile_dialogue_sessions_student_id'), 'profile_dialogue_sessions', ['student_id'], unique=False)
    op.create_table('profile_dialogue_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('slot', sa.String(length=50), nullable=True),
    sa.Column('is_relevant', sa.Boolean(), nullable=True),
    sa.Column('should_advance', sa.Boolean(), nullable=True),
    sa.Column('extracted_fields_json', sa.JSON(), nullable=True),
    sa.Column('agent_result_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['profile_dialogue_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_dialogue_messages_id'), 'profile_dialogue_messages', ['id'], unique=False)
    op.create_index(op.f('ix_profile_dialogue_messages_session_id'), 'profile_dialogue_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_profile_dialogue_messages_student_id'), 'profile_dialogue_messages', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_dialogue_messages_student_id'), table_name='profile_dialogue_messages')
    op.drop_index(op.f('ix_profile_dialogue_messages_session_id'), table_name='profile_dialogue_messages')
    op.drop_index(op.f('ix_profile_dialogue_messages_id'), table_name='profile_dialogue_messages')
    op.drop_table('profile_dialogue_messages')
    op.drop_index(op.f('ix_profile_dialogue_sessions_student_id'), table_name='profile_dialogue_sessions')
    op.drop_index(op.f('ix_profile_dialogue_sessions_status'), table_name='profile_dialogue_sessions')
    op.drop_index(op.f('ix_profile_dialogue_sessions_id'), table_name='profile_dialogue_sessions')
    op.drop_table('profile_dialogue_sessions')
    # ### end Alembic commands ###
