"""rename_nickname_to_name_in_users

Revision ID: 36dd07a4f452
Revises: 029d508054c9
Create Date: 2026-05-21 19:24:12.879134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '36dd07a4f452'
down_revision: Union[str, Sequence[str], None] = '029d508054c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=True))

    # 数据迁移：将 nickname 的值复制到 name 列
    op.execute("UPDATE users SET name = COALESCE(nickname, username) WHERE name IS NULL")

    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))

    # 数据回滚：将 name 的值复制回 nickname 列
    op.execute("UPDATE users SET nickname = name WHERE nickname IS NULL")

    op.drop_column('users', 'name')
    # ### end Alembic commands ###
