"""add_streaming_and_session_fields_to_profile_dialogue

Revision ID: 89739d0f2742
Revises: e640fcc4f3ae
Create Date: 2026-05-28 18:32:08.676543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '89739d0f2742'
down_revision: Union[str, Sequence[str], None] = 'e640fcc4f3ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_dialogue_messages', sa.Column('stream_status', sa.String(length=50), nullable=True))
    op.add_column('profile_dialogue_messages', sa.Column('partial_content', sa.Text(), nullable=True))
    op.add_column('profile_dialogue_messages', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('profile_dialogue_sessions', sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('profile_dialogue_sessions', sa.Column('ended_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('profile_dialogue_sessions', sa.Column('end_reason', sa.String(length=50), nullable=True))
    op.add_column('profile_dialogue_sessions', sa.Column('stream_status', sa.String(length=50), nullable=True))
    op.alter_column('profile_dialogue_sessions', 'status',
               existing_type=mysql.VARCHAR(length=30),
               comment=None,
               existing_comment='collecting / ready_to_confirm / completed / cancelled',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile_dialogue_sessions', 'status',
               existing_type=mysql.VARCHAR(length=30),
               comment='collecting / ready_to_confirm / completed / cancelled',
               existing_nullable=False)
    op.drop_column('profile_dialogue_sessions', 'stream_status')
    op.drop_column('profile_dialogue_sessions', 'end_reason')
    op.drop_column('profile_dialogue_sessions', 'ended_at')
    op.drop_column('profile_dialogue_sessions', 'last_active_at')
    op.drop_column('profile_dialogue_messages', 'completed_at')
    op.drop_column('profile_dialogue_messages', 'partial_content')
    op.drop_column('profile_dialogue_messages', 'stream_status')
    # ### end Alembic commands ###
